### PR TITLE
Add NeoForge Data Generators

### PR DESCRIPTION
**Pull request by ChampionAsh5357**
The following adds data generators for biome modifiers, structure modifiers, and data maps within NeoForge. I have left the unused `version` parameter as in 1.21.2, the carving generation step is removed, so the biome modifier will change depending on that.

There is technically one inaccuracy since it doesn't seem like the choice node can choose between two object types. Specifically, each value within a data map can either look like:
```json5
"example:object": {
    "data": 1
}
```
or
```json5
"example:object": {
    "replace": true.
    "value": {
        "data": 1
    }
}
```

If there is a method to switch based on this context that I am missing, please let me know and I will update accordingly.

### CODE REVIEW

**Comment by misode** [comment]
@ChampionAsh5357 The `ChoiceNode` allows you to optionally define a custom `match` function, for example you could use this to match the second variant
```ts
{
  match: (v: any) => v.value !== undefined,
  priority: 1,
  // ...
}
```

**Comment by ChampionAsh5357** [comment]
Thanks for the help. There is a bit of weirdness when it comes to matching when values are null, but everything works properly when there is some value specified.

**Review by misode — APPROVED** [review]
@ChampionAsh5357 Let me know when they are ready, and I can merge!

**Comment by ChampionAsh5357** [comment]
Everything looks good! Thank you for you help and commits to fix my oversights!

**Pull request merged**
